1.7 Feature: Created server setup menu, sourced it to main, currently available functionalities are to list applications to be installed and bulk installing them with tracking on which got installed and which did not.

diff --git a/lib/user-menu b/lib/user-menu
--- a/lib/user-menu
+++ b/lib/user-menu
@@ -86,10 +86,6 @@ user_add_group(){
         	possibleGroups+=("$groupName")
     	done < /etc/group	
 
-	for item in "${possibleGroups[@]}"; do
-		echo "$item"
-	done
-
 	local groupPresent
 	groupPresent=0
 
@@ -136,6 +132,6 @@ user_add_group(){
 	done
 
 	echo "Adding $userName to $groupToAdd"
-	adduser $userName $groupToAdd && echo "User successfully added!"
+	adduser $userName $groupToAdd && echo "User successfully added!" || echo "Error! Could not add User to $groupToAdd successfully..." && exit 1
 	)
 }
