1.14: Feature - Fully functional multiple-user-delete option in user menu complete.

diff --git a/lib/user-menu b/lib/user-menu
--- a/lib/user-menu
+++ b/lib/user-menu
@@ -13,7 +13,6 @@ user_menu_actions() {
 			4) user_add_group ;;
 			5) multiple_user_create ;;
 			6) multiple_user_delete ;;
-			#6) multiple_user_add_group ;;
 			q) main_menu ;;
 		esac
 	done
@@ -126,8 +125,20 @@ multiple_user_delete(){
 	echo "============================================================="
 	echo "File format is a simple list with each username on a new line!"
 	echo "============================================================="
-	read -p "Please provide the full path to the file with listed users."
-
+	read -p "Please provide the full path to the file with listed users: " filepath
+	
+	if ! cat ${filepath} &>/dev/null; then
+		echo "File not found"
+		return
+	fi
+	
+	while read -r line; do
+		if [[ "$line" != "$(whoami)" ]] && [[ "$line" != "root" ]]; then
+			echo "Deleting ${line}..."
+			sleep 1
+			userdel -r $line 2>/dev/null || echo "Cannot delete user ${line}"
+		fi
+	done < ${filepath}  
 
 }
 
